import React, { Suspense } from "react";

export const metadata = {
	title: "Task Management  | Your Tasks",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<Suspense fallback="Loading...">
			<html lang="en">
				<body suppressHydrationWarning>
					{children}
				</body>
			</html>
		</Suspense>
	);
}