import Footer from "@/components/Footer/page";
import Header from "@/components/Header/page";
import React from "react";

export const metadata = {
	title: "Task Management  | About",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body suppressHydrationWarning>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}