import React from "react";
import "./globals.css";
import AuthContextProvider from "./contexts/AuthContext";

export const metadata = {
	title: "Task Management  | Home",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body suppressHydrationWarning>
				<AuthContextProvider>
					{children}
				</AuthContextProvider>
			</body>
		</html>
	);
}